name: vpv
adopt-info: vpv
summary: Image viewer
description: |
  Image viewer for image processing experts

base: core18
grade: stable
confinement: strict

parts:
  vpv:
    build-snaps: [cmake]
    plugin: cmake
    source: https://github.com/kidanger/vpv.git
    source-type: git
    source-branch: dev
    configflags:
    - -DCMAKE_BUILD_TYPE=Release
    - -DUSE_GDAL=ON
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    build-packages:
    - g++
    - make
    - libsdl2-dev
    - libpng-dev
    - libtiff-dev
    - libjpeg-dev
    - libgdal-dev
    stage-packages:
    - libasound2
    - libasyncns0
    - libflac8
    - libgl1
    - libglvnd0
    - libglx0
    - libjbig0
    - libjpeg-turbo8
    - libogg0
    - libpng16-16
    - libpulse0
    - libsdl2-2.0-0
    - libsndfile1
    - libsndio6.1
    - libtiff5
    - libvorbis0a
    - libvorbisenc2
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libx11-6
    - libxau6
    - libxcb1
    - libxcursor1
    - libxdmcp6
    - libxext6
    - libxfixes3
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxrender1
    - libxss1
    - libxxf86vm1
    - libaec0
    - libarmadillo8
    - libarpack2
    - libasn1-8-heimdal
    - libcurl3-gnutls
    - libdap25
    - libdapclient6v5
    - libepsilon1
    - libfontconfig1
    - libfreetype6
    - libfreexl1
    - libfyba0
    - libgdal20
    - libgeos-3.6.2
    - libgeos-c1v5
    - libgeotiff2
    - libgfortran4
    - libgif7
    - libgssapi3-heimdal
    - libhcrypto4-heimdal
    - libhdf4-0-alt
    - libhdf5-100
    - libheimbase1-heimdal
    - libheimntlm0-heimdal
    - libhx509-5-heimdal
    - libicu60
    - libkmlbase1
    - libkmldom1
    - libkmlengine1
    - libkrb5-26-heimdal
    - liblcms2-2
    - libldap-2.4-2
    - libltdl7
    - libminizip1
    - libmysqlclient20
    - libnetcdf13
    - libnghttp2-14
    - libnspr4
    - libnss3
    - libodbc1
    - libogdi3.2
    - libopenjp2-7
    - libpoppler73
    - libpq5
    - libproj12
    - libpsl5
    - libqhull7
    - libquadmath0
    - libroken18-heimdal
    - librtmp1
    - libsasl2-2
    - libspatialite7
    - libsuperlu5
    - libsz2
    - liburiparser1
    - libwebp6
    - libwind0-heimdal
    - libxerces-c3.2
    - libxml2
    - odbcinst1debian2
    - libblas3
    - liblapack3

apps:
  vpv:
    command: vpv
    plugs:
    - opengl
    - desktop
    - desktop-legacy
    - home
    - network
    - process-control
    - x11
    - wayland
    - pulseaudio
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      MESA_GLSL_CACHE_DIR: "$SNAP_USER_DATA"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
